# Generated by Django 2.1.5 on 2019-02-06 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_addr', models.CharField(max_length=100, null=True)),
                ('current_ip', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host')),
            ],
        ),
    ]
